name: run-scheduled
on:
  schedule:
  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
            python-version: 3.7
      - name: install black
        run: pip3 install black
      - name: run black
        run: black .
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
